before:
  hooks:
    - go mod download
builds:
- goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
    - arm64
  ldflags: -X github.com/jaxxstorm/change-aws-credentials/pkg/version.Version={{.Version}}
  binary: change-aws-credentials
  main: main.go
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  prerelease: auto

