builds:
  - main: main.go
    binary: change-aws-credentials
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
dockers:
  - image: jaxxstorm/change-aws-credentials
