builds:
  - main: main.go
    binary: change-aws-credentials
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
#sign:
# artifacts: all
brew:
  github:
    owner: jaxxstorm
    name: homebrew-tap
  commit_author:
    name: Lee Briggs
    email: lee@leebriggs.co.uk
  folder: Formula
  test: |
    system "#{bin}/change-aws-credentials version"
  homepage: "https://leebriggs.co.uk/"
  description: "A simple tool to change your AWS credentials quickly from the commandline"
dockers:
  -
    binary: change-aws-password
    image: jaxxstorm/change-aws-password
    latest: true
fpm:
  vendor: Lee Briggs
  homepage: https://leebriggs.co.uk
  maintainer: Lee Briggs <lee@leebriggs.co.uk>
  description: "A simple tool to change your AWS credentials quickly from the commandline"
  license: MIT
  formats:
    - deb
    - rpm
